#!/bin/bash

export theme_variant=$1

sudo -E bash <<'EOF'

mkdir -p /usr/share/{themes,icons}/"$theme_variant"

getSourceDir() { echo "$(dirname "$(readlink -f "$0")")" ;}

cd "$(getSourceDir)"

cp -a ./"$theme_variant"/theme/* /usr/share/themes/"$theme_variant"
cp -a ./"$theme_variant"/icons/* /usr/share/icons/"$theme_variant"

gtk-update-icon-cache /usr/share/icons/"$theme_variant"

EOF
